name: Compilar Engine FNF para Web
on:
  push:
    branches: [ main, master ]
  workflow_dispatch: # Permite que você clique em um botão para compilar quando quiser

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o Código
        uses: actions/checkout@v4

      - name: Instalar o Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4 # Versão recomendada para FNF

      - name: Configurar Pastas do Haxe
        run: |
          haxelib setup ~/haxelib

      - name: Instalar Bibliotecas Base (Flixel e Lime)
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel

      - name: Instalar Bibliotecas Específicas do FNF Plus
        run: |
          haxelib git funkin.vis https://github.com
          haxelib git grig.audio https://github.com
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install tjson

      - name: Compilar para HTML5 (Web)
        run: |
          haxelib run lime build html5 -release

      - name: Enviar o Jogo Pronto (Zip)
        uses: actions/upload-artifact@v4
        with:
          name: jogo-fnf-web
          path: export/release/html5/bin/
